source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'dragonfly', '~> 1.0.0'
gem 'faraday-http-cache'
gem 'faraday_middleware'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'geokit'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mysql2'
gem 'omniauth-github'
gem 'omniauth-linkedin'
gem 'rails', '4.2.1'
gem 'recruiter', git: 'git@github.com:guiman/recruiter.git'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.0.0'
gem 'will_paginate-foundation'
gem 'open_uri_redirections'
gem 'sidekiq'
gem 'sinatra'
gem 'google_visualr', '>= 2.5'
gem 'rest-client'

gem 'unicorn'

group :test do
  gem 'byebug'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'web-console', '~> 2.0'
  gem 'webmock'
end
